In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [3]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [4]:
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list, columns=col)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [11]:
df2[['Name', 'Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

create new col

In [22]:
df2["Desigination"] = ['Doctor','Engg.','Doctor','Engg.']
df2

    Name  Age      City  Salary Desigination
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000        Engg.
2  Peter   29    Berlin   62000       Doctor
3  Linda   42    London   85000        Engg.

remove col

In [17]:
df2.drop("Desigination", axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2.drop("Desigination", axis=1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df2.drop(0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [31]:
df2.loc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

In [32]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [26]:
df2.iloc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [33]:
df2.iloc[[0,1],[2,3]]

       City  Salary
0  New York   65000
1     Paris   70000

In [34]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [38]:
df2[(df2['Age'] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000